# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'simple_contacts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Contact')),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
    ]
